// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8t3tpwCjSj28Yqu0jpeC08y99IrgtZWc',
    appId: '1:185177912136:web:09f808212434aa64fc397d',
    messagingSenderId: '185177912136',
    projectId: 'warehouse-app-d8f30',
    authDomain: 'warehouse-app-d8f30.firebaseapp.com',
    storageBucket: 'warehouse-app-d8f30.firebasestorage.app',
    measurementId: 'G-BS8HN18X3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGPR05EwlUcA3rDeymvVwqK2XznPG3yho',
    appId: '1:185177912136:android:5d4c512d229db878fc397d',
    messagingSenderId: '185177912136',
    projectId: 'warehouse-app-d8f30',
    storageBucket: 'warehouse-app-d8f30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTuXtpIw-NzVY8yUDHiGUBea8yZTWCtw',
    appId: '1:185177912136:ios:c74995a2cf4b58fafc397d',
    messagingSenderId: '185177912136',
    projectId: 'warehouse-app-d8f30',
    storageBucket: 'warehouse-app-d8f30.firebasestorage.app',
    iosBundleId: 'com.example.warehouseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmTuXtpIw-NzVY8yUDHiGUBea8yZTWCtw',
    appId: '1:185177912136:ios:c74995a2cf4b58fafc397d',
    messagingSenderId: '185177912136',
    projectId: 'warehouse-app-d8f30',
    storageBucket: 'warehouse-app-d8f30.firebasestorage.app',
    iosBundleId: 'com.example.warehouseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8t3tpwCjSj28Yqu0jpeC08y99IrgtZWc',
    appId: '1:185177912136:web:65604a9726d4bfe6fc397d',
    messagingSenderId: '185177912136',
    projectId: 'warehouse-app-d8f30',
    authDomain: 'warehouse-app-d8f30.firebaseapp.com',
    storageBucket: 'warehouse-app-d8f30.firebasestorage.app',
    measurementId: 'G-K2VKE0E6B3',
  );
}
